name: Github to AWS CodeCommit Sync

on:
  push:
    branches:
      - main

jobs:
  sync-to-codecommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync to AWS CodeCommit
        uses: tsgit18/sync-up-to-codecommit-action@v1.0.6
        with:
          repository_name: AWS-S3-CloudConnexa-Log-Streaming-to-CloudWatch
          aws_region: us-east-2
